import { defineConfig, globalIgnores } from 'eslint/config'
import globals from 'globals'
import js from '@eslint/js'
import pluginVue from 'eslint-plugin-vue'
// import skipFormatting from '@vue/eslint-config-prettier/skip-formatting'

export default defineConfig([
  {
    name: 'app/files-to-lint',
    files: ['**/*.{js,mjs,jsx,vue}'],
  },

  globalIgnores(['**/dist/**', '**/dist-ssr/**', '**/coverage/**']),

  {
    languageOptions: {
      globals: {
        ...globals.browser,
      },
    },
  },
  {
    rules: {
      'no-console': 'warn',
      'no-debugger': 'warn',
      'spaced-comment': 'error',
      'comma-dangle': ['error', 'always-multiline'],
      'comma-spacing': ['error', { 'before': false, 'after': true }],

      'no-spaced-func': 'error',
      'arrow-parens': ['error', 'as-needed'],
      'arrow-spacing': 'error',
      'computed-property-spacing': ['error', 'never'],
      'brace-style': ['error', '1tbs', { allowSingleLine: true }],
      'block-spacing': 'error',
      'dot-notation': 'error',
      'func-call-spacing': ['error', 'never'],
      'function-call-argument-newline': ['error', 'consistent'],
      'function-paren-newline': ['error', 'multiline'],
      'indent': ['error', 2],
      'key-spacing': ['error', { 'beforeColon': false, 'afterColon': true }],
      'keyword-spacing': ['error', { 'before': true, 'after': true }],
      'max-statements-per-line': ['error', { 'max': 2 }],
      'no-extra-parens': ['error', 'all'],
      'no-multi-spaces': 2,
      'no-multiple-empty-lines': [2,
        { 'max': 1 }],
      'no-trailing-spaces': 'error',
      'no-whitespace-before-property': 'error',
      'object-curly-newline': ['error', { 'multiline': true }],
      'object-curly-spacing': ['error', 'always'],
      'operator-linebreak': [2,
        'after',
        {
          'overrides': {
            '?': 'before',
            ':': 'before',
          },
        }],
      'padded-blocks': ['error', 'never'],
      quotes: ['error', 'single'],
      'rest-spread-spacing': ['error', 'never'],
      'semi': 'off',
      'semi-spacing': [2,
        {
          'before': false,
          'after': true,
        }],
      'semi-style': ['error', 'last'],
      'space-before-blocks': [2, 'always'],
      'space-before-function-paren': [2, 'never'],
      'space-in-parens': [2, 'never'],
      'space-infix-ops': 2,
      'space-unary-ops': [2,
        {
          'words': true,
          'nonwords': false,
        }],

      'default-case': 'error',
      'switch-colon-spacing': ['error', { 'after': true, 'before': false }],
      'template-curly-spacing': ['error', 'never'],
      'no-unneeded-ternary': [2,
        { 'defaultAssignment': false }],
      'valid-typeof': 2,
      'array-bracket-spacing': [2,
        'never'],

      'array-bracket-newline': ['error', 'consistent'],
      'array-element-newline': ['error', 'consistent'],
      'jsx-quotes': 'error',
      'no-new-wrappers': 2,
      'no-unused-vars': 'off',

      'eqeqeq': ['error', 'always'],
      'no-else-return': 'error',
      'no-empty': 'warn',
      'no-var': 'error',
      'object-shorthand': 'error',
      'prefer-template': 'error',
      'no-prototype-builtins': 'off',

      'vue/brace-style': 'error',
      'vue/arrow-spacing': 'error',
      'vue/attribute-hyphenation': ['error', 'always'],
      'vue/first-attribute-linebreak': ['error',
        {
          singleline: 'ignore',
          multiline: 'below',
        }],
      'vue/html-closing-bracket-newline': ['error',
        {
          singleline: 'never',
          multiline: 'always',
        }],
      'vue/html-self-closing': ['error',
        {
          html: {
            void: 'any',
            normal: 'always',
            component: 'always',
          },
        }],
      'vue/max-attributes-per-line': ['error', {
        singleline: { max: 6 },
        multiline: { max: 1 },
      }],
      'vue/no-use-v-if-with-v-for': ['error',
        { allowUsingIterationVar: true }],
      'vue/html-indent': ['error',
        2,
        {
          attribute: 1,
          baseIndent: 1,
          closeBracket: 0,
          alignAttributesVertically: true,
          ignores: [],
        }],
      'vue/v-bind-style': ['error', 'shorthand'],
      'vue/v-on-style': ['error', 'shorthand'],
      'vue/require-explicit-emits': ['error',
        { allowProps: true }],
      'vue/v-on-event-hyphenation': ['error', 'always', { autofix: true }],
      'vue/require-default-prop': 'off',
      'vue/no-unused-components': 'warn',
      'vue/no-mutating-props': 'off',
      'vue/require-prop-types': 'off',
      'vue/multi-word-component-names': 'off',
      'vue/component-name-in-template-casing': ['error',
        'PascalCase',
        {
          registeredComponentsOnly: true,
          ignores: [],
        }],
      'vue/component-definition-name-casing': ['error', 'PascalCase'],
      'vue/component-options-name-casing': ['error', 'PascalCase'],
      'vue/html-comment-content-spacing': ['error', 'always'],
      'vue/match-component-import-name': 'warn',
      'vue/no-duplicate-attr-inheritance': 'warn',
      'vue/no-potential-component-option-typo': 'error',
      'vue/no-this-in-before-route-enter': 'error',
      'vue/no-unused-properties': 'warn',
      'vue/no-undef-properties': 'off',
      'vue/no-useless-v-bind': ['error',
        {
          ignoreIncludesComment: true,
          ignoreStringEscape: true,
        }],
      'vue/padding-line-between-blocks': ['error', 'always'],
      'vue/prefer-separate-static-class': 'error',
      'vue/require-name-property': 'error',
      'vue/v-on-function-call': 'error',
      'vue/singleline-html-element-content-newline': 'off',
    },
  },

  js.configs.recommended,
  ...pluginVue.configs['flat/essential'],
  // skipFormatting,
])
